apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - homepage.lab.local
      secretName: homepage-lab-local-tls
  rules:
    - host: homepage.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 80
