---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: replicate-api
  namespace: fotobudka
spec:
  encryptedData:
    REPLICATE_API_TOKEN: AgAE0oLSugiX7EL+VSlwb04YclUv77W1Fqb8FQ3eBAtqJvl4jvX/2vcjPHyOG6+RN8/trWLlSwPfZ1gZtiOzK4tRcv2SYPv1iOVh7GepcA3gw2BmM+WZzeAWLIgThIFSZFW+GXEOyr1bk11nLAADUxZEtdhtOgz7kZYNSJwCER7/RF30wyU0Pt+bZ06FK+4zuh4Zpe1ETtroPRQMOCvdkJAuc9ohz49IWaVfyO4G9WzX58K3mmxi/ov12eLDv6wRmJASTpNxTP+DC1tc6y0SNRuklu7uiGrHDDdBMu/WO7MwHTC6hFpS+PjhiSDs8yJEHBgvONpLPJCmC6OANydZEbKbZFQVHHZHYKzHsMR8yPrl6Z7xjKyihmPotiA3GkM8qBgSzY3hKQQ3692JpKWyy1l9oix2dmrxc7AlxuGjBtdT8p4Yuk237Q0db+uho/ucrueo/QmaKyaJ8g5CFNa1HZREb02OVg3pcJRRLSdMz4dlhigq64tpgSaflPXvWkTStq/DBjm66XOfhW7mdnFFz11jKWlLSZ4S0H2tKiuCnW7A7yWv4XIFeJFV3RqJImkGbo9qIR9DZ9Kc/NpG2nem8E+A/7fZ0s0sb+TwRJe7Tss+5U6BfIrWozdeu+2nJuu8BPHw7xHEqkTkW56sLQMvUcGNAypULM69lPZhT7UyoFUBBS3Emew3bFyLJPmhPHkAjxFX8G10djwCtX9jsaChySDNyLVcP4lAmsk3yup0bZovHIb5C5BseoeT
  template:
    metadata:
      name: replicate-api
      namespace: fotobudka
    type: Opaque
