apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fotobudka-data
  namespace: fotobudka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
