---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx-demo-secret
  namespace: nginx-demo
spec:
  encryptedData:
    DEMO_PASSWORD: AgBbhrcB4DPUkOOStITnoYVH3pIFFwiwpv/cHjnKXZzH2Fu7xnTgbAEb9JJFtVX3T/AkkFPYuP2GvlDfj7cl9tRXFcynJnt6tO2xrYGtrz25sz3NFhzYb34nOWeie9LqcUbO0sb0dMOX9ltuHgjha7KimmMZzL1iEsJ4Bin9JP2aCF/+tHLYr0I3wELV8Do4+V++Gyz0LuFRSXgl3309CK+E7s8MyZrhpiUSUD7MbT67hkGn3uxqM7PGUCZC3mkd8FVnIi/AVnC0TGpDnfk/9crfOJUDIRGIdCkRzyTn48jdKwdS13eSKaMj1YmB/vR4hpla1T+GLBTIFN3c2vhwvi//a74CVKn8VPwzIRHXl5Eeb/7h4brUpzWUq+qz1MuWXRILgp2jAFpT8gEAbfDClKAQ4D1L1Ntb18cnxq9P+TyNoiFRb3qZfMf9HBOSuzcgftxR9toxxBp0IEEmz01tSJN5ULZLylOm7RSbylgT6HkEnAtP31VHeJsax4s6JvJcbFEuu9R9BwbfX15WMwoxOL4SI2uQJe9Z3VmbC1EwuDGA7SYqUhYQYjmksasp9GdGSbRYXX17jRroL+DHphjmQ+kXlj+kOXZPuqgmFK6dhyieaUoGUYQwHNrjJO7TySsF/gC71Ex2jsEanCebo6zEIDVZ/YSNZ5n28lA7vpdA2iph0cjid4AyBDU6cfZMx5K8o9iVx+Xq2of56RLeB6iPVD6ha5XSLaI=
    DEMO_USERNAME: AgA6lyMLXlrNVwIrIyG+DEWN0wlNeINJLF4qpOgB0yHtuQbkc1qThDCLfeZmUX46Eujons7VzgmZ/d1w65HX5+e0lEHwUZZY+onpQWBIz+OOCINmMaANkewWwY6GE0C3JhB0naYQohRTc1IZDM78Mjf7a8ASLfX8fw3WJuvUycMukHo3nbnWJzQxH2JQkg0E75JEfi7A3ZBMPHYqUNumh5fr+30n5zZ8NRyQEzEC0a0YNHcU75WUG44yDhzRb5aigtvjebsQbVe8wKAWL1YdEFv34Iyf80AY/z2WxJbZmXXUuZSnjq4llfoSwZiElBUs0cB0HlFbKID7niYVeDlC3jqXRMtqS2u4/is9VchsoBGqy7+LeZYs8/i907PkqNLVVm2WdhpgajJZfCNj2mM2DncN3wuQ8hZo2gtOhlbSI1cUtJkzua2LRjXurlvrp1bDaj5q3ts1gFJYjJGs5f3Zh9hcCpJKk2wAiocLBbfBDMoG70ma0q9npRiRrJktn4flN97FgYndKN/8UXkYr1Ek1FtTrlB/7DfXJfC3aCijoqhRzEeMKHANRv+jWgNeYZqZvteLnZMbYOLamRGd0svb2e0gUVgCn92P2SQNhLugjcla2XNHnQlm6KdTS7wu77WkqF+GPgKH6DBJVJ3THfOSADgmbtHauTXZCrS2cAO1gRuhXBiUQX/aod+cNoaoSmHV8yfej3Uq
  template:
    metadata:
      name: nginx-demo-secret
      namespace: nginx-demo
