---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helpdesk-app-secret
  namespace: helpdesk
spec:
  encryptedData:
    FLASK_SECRET_KEY: AgAVbjOaQGDo/1uZSFW/fBys//EMwQ4SsZClZeqBwlA2cziL/23WCrgH3mMLwbehlET6VPul9Z8QfMbXlRW1N1AgDKBF5ZpA4V8qMu9DlVSxW2XsbX//YvI1mMOiK8GiNo7lsb1zsauwsBW8uI0Vd/xnDudnuSHZHosZUfJHa8Xs5LV0Q2PUm5ocbgZ4ZZbPqNRkg9g6A44DHokgSAph1fityXdEHEKTegaI3MY6R0lvwV+Lfoh3GjTWgQzrU8GRQ9LkW1b0iMbkTZg7LAA7CT/IZ4i36jDMA3B5jZutIHhuK/VhR6jDnriQLfZUeCZjHMSEbDwtq5ysCYlHTxwJ/CbIMOvLQkkzlVkkq7JspzISoMpOCxfqXvglZKMp081sFcmXB3ha6T5iQVqGDJnpPGI2nPNTSfrrAWwAUK7TqAdyqjBO5si3rDWoIckkAUMRwgYrNk8hEkFnbpr18l4BzV5GlMsc7+c3ALVCIO4+JrK23xCzeW15fVvWBSO1UONWdCxlVhfqc0BgePFQyX248RM8FybiM28xGuKkLaRpSFYAgXSse/4w+p2dDRCdx58JQADxiK1RJUCadVq/TE6MXq8TuCeBq6fBdC4ShfwC0S3yd7hcc41OpTzqGGRu8ezvb0g6YyUFZ+CwEBZ6cXfTLP1K2ATNgVliFf/oSPBuEQBJ3W99IBlbV7uch6Y+Cjb4FYij++p5RkYHRRSJ360cKTCPYiEI5x+fDvvQQrrXNS7WLt+x7m665i/C1k3Zb+oQcQsX2zYxefJimI2y1Htb8Bta
  template:
    metadata:
      name: helpdesk-app-secret
      namespace: helpdesk
