---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helpdesk-app-secret
  namespace: helpdesk
spec:
  encryptedData:
    FLASK_SECRET_KEY: AgCOci1GOMr25WN8J79/ecdONvVb1bugv7vrRcK2+uG3CwoclpdaQCY8HsrJRkDb7gNzxSq0HQnt/xoRHyUW2nr0DwLp+UdpR6/r3PE/pTQ/4h8krFETe7bnue8LfdTG3jORV5QrPhAj9NsCmur6e0jYxgWyVkuy4yFlGeyEWGELjFnm4tYp8moqyA0vAcdZPkNa8lkPLFqLLTHQ1Eoh3T8N6EPff4tmcwkM6854yArNPewmqHW49g+nr8HAsG+54rXJ/6q2GUS279UJVwQ22B7JJ5aHkVVAJWRmUqWykyD0ERJd3ucKPGkIVE1xgukrZkZ2uHNT+IGktOgnMZrRVn8ijARqBnGu43WCu1TdkjDXz8k/qhuGd50+1IdsL6+ZQgc5IfdGiDfsmJOPP0Oegd8DRSW4xuWWl4Pmv9oCCKTAEoJ1YMSMQa1NG8HZ8ZAbA5WQWBHqzd+R/MWVEt6tb456J6qbdb4aQxwmRZtbw/Jh6uo244DTDkA5DS5B2w0ch7nigh1vZQIjQvShGhy6Gu67lHg6a5A/6E7jh9D9iQ0EDjcqOIfvt8qjTnmbb/oeZ6KVkhr20dVmmFYPnzOyn8vBWIvXB7gsBp3X5giEvbBfjkIntAMLrqLMQQU/qznUqosiQbXiDYmWvnEHCmLfko/jOQZ5auErl3okiVcL2gTHwml9MQykzY6tj1/Rd36xtNbFgQ+TSbGlKtCcKDon5vMEdELPYEnOEzDaIjynUe7WLQGaHDSTeosJpT5dJqYPGqsHdW+WGV6io6N7+w6ojYAx
  template:
    metadata:
      name: helpdesk-app-secret
      namespace: helpdesk
